404view
ArastoSahbaei/codic-education-website pull request #100
Opened 2021-09-13 11:58 UTC by UlrikaLif

Have added a countdown and redirect to initialView.
CountDown har a 30 seconds time frame.

2021-09-14 13:29 UTC, ArastoSahbaei requested changes

2021-09-14 13:29 UTC, ArastoSahbaei commented on package.json
> +    "react-countdown": "^2.3.2",
behöver tas bort. npm `uninstall react-countdown`

2021-09-14 13:29 UTC, ArastoSahbaei commented on src/routes/Routes.tsx
> +import { Error404View } from '../view/error404/Error404View'
Kan flyttas upp några rader så att import strukturen bibehålls :)

2021-09-14 13:29 UTC, ArastoSahbaei commented on src/routes/Routes.tsx
> +				<Route component={Error404View} />        {/* Default View */}
Rad **83** kommer inte att behövas.
HomeView finns redan som initial så ifall man besöker en inaktuell URL så navigeras man om till startsidan.

2021-09-14 13:29 UTC, ArastoSahbaei commented on src/view/error404/Error404View.tsx
> +			<CountDownToMove></CountDownToMove>
Kan vara självstängande. `<CountDownToMove />`

2021-09-14 13:29 UTC, ArastoSahbaei commented on src/view/error404/components/CountDownToMove.tsx
> +export const CountDownToMove = () => {
Du kan döpa om komponenten till `CountDown `👍

2021-09-14 13:29 UTC, ArastoSahbaei commented on src/view/error404/components/CountDownToMove.tsx
> +	}
Kan skrivas om till en **ternary**
`timeLeft > 0 ? setTimeLeft(timeLeft - 1) : history.push(RoutingPath.initialView)`

2021-09-14 13:29 UTC, ArastoSahbaei commented on src/view/error404/components/CountDownToMove.tsx
> +	const [timeLeft, setTimeLeft] = useState(delay)
Kan döpas om till `const [timer, setTimer] = useState(30)`

2021-09-14 13:29 UTC, ArastoSahbaei commented on src/view/error404/components/CountDownToMove.tsx
> +		</>
Eftersom att du endast retunerar ett enda dokument så behöver du inte ha fragments. Det räcker med:
`<SmallText> Du kommer automatiskt att förflyttas till startsidan om { timeLeft } sekunder.</SmallText>`

2021-09-14 13:29 UTC, ArastoSahbaei commented on src/view/error404/Error404View.tsx
> +import { CountDownToMove } from './components/CountDownToMove'
importen kan organiseras på följande vis:
först dom med `{ }`
övriga därefter

2021-09-14 13:29 UTC, ArastoSahbaei commented
Glöm inte heller att formatera alla filer med `shift+alt+f` (windows)

2021-09-14 13:35 UTC, ArastoSahbaei requested changes

2021-09-14 13:35 UTC, ArastoSahbaei commented on src/view/error404/Error404View.tsx
> +			<Title> <ColoredParagraph>4</ColoredParagraph> 0 <ColoredParagraph>4</ColoredParagraph> </Title>
Title är en H1
ColoredParagraph är en span

Detta gör att en span är en child till en h1 som inte är bra.

Ett exempel på en lösning skulle kunna vara:
```
			<Title>
				<ColoredParagraph>4</ColoredParagraph>
				<Paragraph>0</Paragraph>
				<ColoredParagraph>4</ColoredParagraph>
			</Title>
```
Varav Title blir en div

2021-09-15 13:30 UTC, UlrikaLif commented on package.json
> +    "react-countdown": "^2.3.2",
Gjort

2021-09-15 13:30 UTC, UlrikaLif commented on src/routes/Routes.tsx
> +				<Route component={Error404View} />        {/* Default View */}
Gjort

2021-09-15 13:30 UTC, UlrikaLif commented on src/view/error404/Error404View.tsx
> +			<CountDownToMove></CountDownToMove>
Gjort

2021-09-15 13:30 UTC, UlrikaLif commented on src/view/error404/components/CountDownToMove.tsx
> +export const CountDownToMove = () => {
Gjort

2021-09-15 13:31 UTC, UlrikaLif commented on src/view/error404/components/CountDownToMove.tsx
> +	/* Change the delay time in seconds here! Started with 30 seconds */
Gjort

2021-09-15 13:31 UTC, UlrikaLif commented on src/view/error404/components/CountDownToMove.tsx
> +	const delay = 30
Gjort

2021-09-15 13:31 UTC, UlrikaLif commented on src/view/error404/components/CountDownToMove.tsx
> +	}
Gjort

2021-09-15 13:31 UTC, UlrikaLif commented on src/view/error404/components/CountDownToMove.tsx
> +	const [timeLeft, setTimeLeft] = useState(delay)
Gjort

2021-09-15 13:32 UTC, UlrikaLif commented on src/view/error404/components/CountDownToMove.tsx
> +
Tagit bort överflödiga rader

2021-09-15 13:32 UTC, UlrikaLif commented on src/view/error404/components/CountDownToMove.tsx
> +		</>
Gjort

2021-09-15 13:32 UTC, UlrikaLif commented on src/view/error404/Error404View.tsx
> +import { CountDownToMove } from './components/CountDownToMove'
Ändrat ordning

2021-09-15 13:33 UTC, UlrikaLif commented on src/view/error404/Error404View.tsx
> +			<Title> <ColoredParagraph>4</ColoredParagraph> 0 <ColoredParagraph>4</ColoredParagraph> </Title>
Har gjort om Title till div

2021-09-16 10:48 UTC, merged