Feature/product list checkout #52
ArastoSahbaei/codic-education-website pull request #53
Opened 2021-07-07 15:17 UTC by sebbekarlsson

just adds a simple product list at checkout

2021-07-08 11:54 UTC, ArastoSahbaei requested changes

2021-07-08 16:16 UTC, sebbekarlsson commented on src/components/checkout/product-list/types.ts
> +}
Är det inte schysst med lite ordning och reda och inte blanda in typerna med komponent-koden?
Tycker det är nice att hålla själva komponentkoden så clean som möjligt

2021-07-08 16:37 UTC, ArastoSahbaei commented on src/components/checkout/product-list/types.ts
> +}
smaksak, men sure låt gå.

2021-07-09 18:22 UTC, sebbekarlsson commented
Closing because it's implemented at: https://github.com/ArastoSahbaei/codic-education-website/pull/63

2021-07-09 18:22 UTC, closed without merging